FROM centos:7 as builder
RUN yum install -y golang
COPY . /go/src/kubevirt.io/kubevirt
# osbs multistage squashes everything to one layer and right now only this first stage is supported
RUN export GOPATH=/go && cd /go/src/kubevirt.io/kubevirt/cmd/virt-handler && go build . && mv virt-handler /usr/bin/
RUN yum remove -y golang && rm -rf /go
ENTRYPOINT [ "/usr/bin/virt-handler" ]
USER root
