load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "certificate_controller.go",
        "certificate_controller_utils.go",
    ],
    importpath = "kubevirt.io/kubevirt/pkg/virt-operator/certificates",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/controller:go_default_library",
        "//staging/src/kubevirt.io/client-go/log:go_default_library",
        "//vendor/github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1:go_default_library",
        "//vendor/github.com/cert-manager/cert-manager/pkg/apis/meta/v1:go_default_library",
        "//vendor/github.com/cert-manager/cert-manager/pkg/client/clientset/versioned:go_default_library",
        "//vendor/golang.org/x/time/rate:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/util/runtime:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/util/wait:go_default_library",
        "//vendor/k8s.io/client-go/kubernetes:go_default_library",
        "//vendor/k8s.io/client-go/kubernetes/typed/core/v1:go_default_library",
        "//vendor/k8s.io/client-go/listers/certificates/v1beta1:go_default_library",
        "//vendor/k8s.io/client-go/tools/cache:go_default_library",
        "//vendor/k8s.io/client-go/tools/record:go_default_library",
        "//vendor/k8s.io/client-go/util/workqueue:go_default_library",
        "//vendor/k8s.io/kube-aggregator/pkg/controllers:go_default_library",
        "//vendor/k8s.io/utils/clock:go_default_library",
    ],
)
